#### Load 58 patients datasets

- ***58*** patients data from Oct. 2023 to Dec. 2023, should have all seven features (pressure, flow, volumn, OSI, SpO2, FiO2, Paw)
- 12hrs(before starting date) + 24 hours + 12hrs(after starting date) data for each patient's starting date, need to decide the starting point, which is all seven features showed up.
- one of three ventilators (CDGR or AVEAA or SVU).

In [1]:
# Read 58 csv files iteratively, and summary the statistics for each file.
import pandas as pd

# Initialize a pandas ExcelWriter
with pd.ExcelWriter('a_58_ext_column_statistics.xlsx') as writer:
    # Iterate over the range of file numbers
    for i in range(1, 233):
        # Generate the filename
        filename = f'/nfs/turbo/med-kayvan-lab/Projects/PARDS/02-Data/02-EVENTS/a-CDGR+AVEAA+SVU(58)_20240205/a-58_Extension/a_58_ext_{i:03}.csv'
        # Read the CSV file into a DataFrame
        df = pd.read_csv(filename)
        # Get the number of rows in the DataFrame
        num_rows = len(df)
        # Initialize a dictionary to store column-wise statistics
        column_stats = {}
        # Iterate over each column in the DataFrame
        for col in df.columns:
            # Get the number of non-empty values in the column
            non_empty_values = df[col].count()
            # Get the number of empty values in the column
            empty_values = num_rows - non_empty_values
            # Store the column statistics in the dictionary
            column_stats[col] = {'num_rows': num_rows, 'non_empty_values': non_empty_values, 'empty_values': empty_values}
        # Convert the column statistics to a DataFrame
        stats_df = pd.DataFrame(column_stats)
        # Add the DataFrame to the ExcelWriter with the file name as the sheet name
        stats_df.to_excel(writer, sheet_name=f'sheet_{i:03}', index=False)

In [2]:
# Concatenate all 58 files' statistics to one table
import pandas as pd

# Initialize an empty list to store the DataFrames
dfs = []

# Iterate over the range of sheet numbers
for i in range(1, 233):
    # Generate the sheet nameZ
    sheet_name = f'sheet_{i:03}'
    # Read the sheet into a DataFrame
    df = pd.read_excel('a_58_ext_column_statistics.xlsx', sheet_name=sheet_name)
    # Append the DataFrame to the list
    dfs.append(df)

# Concatenate the DataFrames vertically by stacking them by rows
result_df = pd.concat(dfs, axis=0)

# Generate the row names for every third row
row_names = []
for i in range(1, 233):
    row_names.extend([f'num_rows_{i:03}', f'non_empty_values_{i:03}', f'empty_values_{i:03}'])
    
# Insert the row names into the DataFrame
result_df.index = row_names + [f'extra_{i}' for i in range(len(result_df) - len(row_names))]

# Save the concatenated DataFrame to a CSV file
result_df.to_csv('a_58_ext_column_statistics_concatenated_with_row_names.csv')

In [28]:
# Add "Group" column:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("a_58_ext_column_statistics_concatenated_with_row_names.csv")

# Rename the first column as "File Name"
df.rename(columns={'Unnamed: 0': 'File Name'}, inplace=True)

# Keep only the rows where the "File Name" starts with "non"
df = df[df['File Name'].str.startswith('non')]

# Add a new column "Group" with group numbers
group_size = 4
df['Group'] = (df.index // group_size) + 1

# Save the DataFrames to CSV files
df.to_csv('a_58_ext_column_statistics_concatenated_with_row_names.csv', index=False)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 232 entries, 0 to 231
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   File Name                        232 non-null    object
 1   Relative Time (sec)              232 non-null    int64
 2   Time                             232 non-null    int64
 3   Oxygenation Saturation Index     232 non-null    int64
 4   AVEA - eVT                       232 non-null    int64
 5   AVEA - FiO₂                      232 non-null    int64
 6   AVEA - Paw                       232 non-null    int64
 7   AVEA - Auxiliary Waveform        232 non-null    int64
 8   AVEA - Air Flow Wave             232 non-null    int64
 9   CDGR - FiO₂                      232 non-null    int64
 10  CDGR - Paw                       232 non-null    int64
 11  CDGR - eVT                       232 non-null    int64
 12  CDGR - Flow                      232 non-null    int64
 13  CDGR - iPress Wave               232 non-null    int64
 14  SVU - Front Panel Button Status  232 non-null    int64
 15  SVU - Ptrans Wave                232 non-null    int64
 16  GE - SpO2 1                      232 non-null    int64
 17  Group                            232 non-null    int64
dtypes: int64(17), object(1)
memory usage: 34.4+ KB

In [30]:
df.tail()

,File Name,Relative Time (sec),Time,Oxygenation Saturation Index,AVEA - eVT,AVEA - FiO₂,AVEA - Paw,AVEA - Auxiliary Waveform,AVEA - Air Flow Wave,CDGR - FiO₂,CDGR - Paw,CDGR - eVT,CDGR - Flow,CDGR - iPress Wave,SVU - Front Panel Button Status,SVU - Ptrans Wave,GE - SpO2 1,Group
227,non_empty_values_228,4249081,4249081,4249081,0,0,0,0,0,4248991,4248991,4248991,4249080,4249080,0,0,4249036,57
228,non_empty_values_229,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,58
229,non_empty_values_230,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,58
230,non_empty_values_231,1048329,1048329,357653,1025070,1025271,1025271,0,1048329,0,0,0,0,0,0,0,1014521,58
231,non_empty_values_232,3732674,3732674,3732674,3732674,3732674,3732674,0,3732673,0,0,0,0,0,0,0,3732514,58

#### Load 151 patients datasets

- ***151*** patients data from Jan. 17th, 2023 to Sep. 2023, pulling seven features (pressure, flow, volumn, OSI, SpO2, FiO2, Paw)
- 12hrs(before starting date) + 24 hours + 12hrs(after starting date) data for each patient's starting date, need to decide the starting point, which is all seven features showed up.
- one of three ventilators (CDGR or AVEAA or SVU).

In [16]:
# Read 302 csv files iteratively, and summary the statistics for each file.
import pandas as pd

# Initialize a pandas ExcelWriter
with pd.ExcelWriter('b_151_ext_column_statistics.xlsx') as writer:
    # Iterate over the range of file numbers
    for i in range(1, 605):
        # Generate the filename
        filename = f'/nfs/turbo/med-kayvan-lab/Projects/PARDS/02-Data/02-EVENTS/b-CDGR+AVEAA+SVU(151)_20240205/b-151-Extension/b_151_ext_{i:03}.csv'
        # Read the CSV file into a DataFrame
        df = pd.read_csv(filename)
        # Get the number of rows in the DataFrame
        num_rows = len(df)
        # Initialize a dictionary to store column-wise statistics
        column_stats = {}
        # Iterate over each column in the DataFrame
        for col in df.columns:
            # Get the number of non-empty values in the column
            non_empty_values = df[col].count()
            # Get the number of empty values in the column
            empty_values = num_rows - non_empty_values
            # Store the column statistics in the dictionary
            column_stats[col] = {'num_rows': num_rows, 'non_empty_values': non_empty_values, 'empty_values': empty_values}
        # Convert the column statistics to a DataFrame
        stats_df = pd.DataFrame(column_stats)
        # Add the DataFrame to the ExcelWriter with the file name as the sheet name
        stats_df.to_excel(writer, sheet_name=f'sheet_{i:03}', index=False)

In [18]:
# Concatenate all 302 files' statistics to one table
import pandas as pd

# Initialize an empty list to store the DataFrames
dfs = []

# Iterate over the range of sheet numbers
for i in range(1, 605):
    # Generate the sheet nameZ
    sheet_name = f'sheet_{i:03}'
    # Read the sheet into a DataFrame
    df = pd.read_excel('b_151_ext_column_statistics.xlsx', sheet_name=sheet_name)
    # Append the DataFrame to the list
    dfs.append(df)

# Concatenate the DataFrames vertically by stacking them by rows
result_df = pd.concat(dfs, axis=0)

# Generate the row names for every third row
row_names = []
for i in range(1, 605):
    row_names.extend([f'num_rows_{i:03}', f'non_empty_values_{i:03}', f'empty_values_{i:03}'])
    
# Insert the row names into the DataFrame
result_df.index = row_names + [f'extra_{i}' for i in range(len(result_df) - len(row_names))]

# Save the concatenated DataFrame to a CSV file
result_df.to_csv('b_151_ext_column_statistics_concatenated_with_row_names.csv')

In [52]:
# Add "Group" column:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("b_151_ext_column_statistics_concatenated_with_row_names.csv")

# Rename the first column as "File Name"
df.rename(columns={'Unnamed: 0': 'File Name'}, inplace=True)

# Keep only the rows where the "File Name" starts with "non"
df = df[df['File Name'].str.startswith('non')]

# Reset the index to re-number from 0 to length(df)
df.reset_index(drop=True, inplace=True)

# Add a new column "Group" with group numbers
group_size = 4
df['Group'] = (df.index // group_size) + 1

# Save the DataFrames to CSV files
df.to_csv('b_151_ext_column_statistics_concatenated_with_row_names.csv', index=False)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   File Name                        604 non-null    object
 1   Relative Time (sec)              604 non-null    int64
 2   Time                             604 non-null    int64
 3   Oxygenation Saturation Index     604 non-null    int64
 4   AVEA - eVT                       604 non-null    int64
 5   AVEA - FiO₂                      604 non-null    int64
 6   AVEA - Paw                       604 non-null    int64
 7   AVEA - Auxiliary Waveform        604 non-null    int64
 8   AVEA - Air Flow Wave             604 non-null    int64
 9   CDGR - FiO₂                      604 non-null    int64
 10  CDGR - Paw                       604 non-null    int64
 11  CDGR - eVT                       604 non-null    int64
 12  CDGR - Flow                      604 non-null    int64
 13  CDGR - iPress Wave               604 non-null    int64
 14  SVU - Front Panel Button Status  604 non-null    int64
 15  SVU - Ptrans Wave                604 non-null    int64
 16  GE - SpO2 1                      604 non-null    int64
 17  Group                            604 non-null    int64
dtypes: int64(17), object(1)
memory usage: 85.1+ KB

In [54]:
df.tail()

,File Name,Relative Time (sec),Time,Oxygenation Saturation Index,AVEA - eVT,AVEA - FiO₂,AVEA - Paw,AVEA - Auxiliary Waveform,AVEA - Air Flow Wave,CDGR - FiO₂,CDGR - Paw,CDGR - eVT,CDGR - Flow,CDGR - iPress Wave,SVU - Front Panel Button Status,SVU - Ptrans Wave,GE - SpO2 1,Group
599,non_empty_values_600,4243234,4243234,4243234,0,0,0,0,0,4243234,4243234,4243138,4243233,4243233,0,0,4243072,150
600,non_empty_values_601,1100,1100,0,0,0,0,0,0,0,0,0,0,0,0,0,1100,151
601,non_empty_values_602,7889,7889,4284,0,0,0,0,0,0,0,0,0,0,0,0,7889,151
602,non_empty_values_603,4244831,4244831,4244831,0,0,0,0,0,4231907,4229585,4229484,4244830,4244830,0,0,4233024,151
603,non_empty_values_604,4263126,4263126,4263126,0,0,0,0,0,4263126,4263126,4263126,4263125,4263125,0,0,4262949,151